/* AUTH */
export const USER_AUTH_START = 'USER_AUTH_START'
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
export const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE'

/* USERS */
export const USERS_GET_START = 'USERS_GET_START'
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS'
export const USERS_GET_FAILURE = 'USERS_GET_FAILURE'
